language: node_js

node_js:
  - "8"

env:
  - PATH=$HOME/.local/bin:$PATH
  - S3_BUCKET=dunkel-pipeline
  - AWS_DEFAULT_REGION=us-east-2

cache:
  directories:
  - node_modules

script:
  - npm run lint
  - npm test

after_success:
  - pip install --user awscli
  - pip install --user aws-sam-cli
  - sam --version
